carla:
  host: "localhost"
  port: 2000
  timeout: 10.0
  town: "Town03"
  fixed_delta_seconds: 0.05
  traffic_manager:
    port: 8000
    synchronous: true
  camera:
    image_width: 1280
    image_height: 720
    fov: 90
    transform:
      location: { x: 1.5, y: 0.0, z: 1.3 }
      rotation: { pitch: -8, yaw: 0.0, roll: 0.0 }

lane_detector:
  resize: [1280, 720]
  canny: { low_thresh: 50, high_thresh: 150 }
  roi:
    y_start_pct: 0.6
    left_pct: 0.0
    right_pct: 1.0
  hough:
    rho: 1
    theta_deg: 1
    threshold: 30
    min_line_len: 40
    max_line_gap: 100
  smoothing_factor: 0.7
  max_missing: 10

validation:
  output_dir: "validation"
  num_captures: 12
  interval_seconds: 10.0
  y_min_pct: 0.6