carla:
  host: "localhost"
  port: 2000
  timeout: 10.0
  town: "Town03"
  FPS: 30
  validation_mode: False
  enable_recording: False
  enable_debugs: False
  enable_traffic: True

lane_detector:
  display_lane_overlay: True
  display_lane_lines : True
  display_center_lane_line : True
  image_resize:
    image_width: 1280
    image_height: 720
  smoothing_factor: 0.9
  max_missing: 20
  gaussian_blur:
    kernel_size_x: 3
    kernel_size_y: 3
    sigma_x: 5
  canny:
    low_thresh: 50
    high_thresh: 150
  hough: 
    rho: 1
    threshold: 30
    min_line_len: 40
    max_line_gap: 100
  bev_lane_detector:
    bev_enabled: False
    bev_size:
      bev_width: 256
      bev_height: 256
    src_pts_frac:
        - [0.0, 1.0]    # bottom-left
        - [1.0, 1.0]    # bottom-right
        - [1, 0.45]     # right horizon
        - [0, 0.45]     # left horizon

validation:
  output_dir: "validation"
  threshold_px: 10
  num_captures: 20
  interval_seconds: 10.0
  y_min_pct: 0.6
  draw_det_vs_gt: True

object_detection:
  model_size: '11s' # 11n does not yield good results I recommend to use at least 11s
  confidence_threshold: 0.5
  nms_threshold: 0.6

sensors:
  front_camera:
    transform:
        location: { x: 1.5, y: 0.0, z: 1.3 }
        rotation: { pitch: -8, yaw: 0.0, roll: 0.0 }
    image_size_x: 1280
    image_size_y: 720
    fov: 90
    bloom_intensity: 0.675
    fstop: 1.4
    iso: 100.0
    gamma: 2.2
    lens_flare_intensity: 0.1
    sensor_tick: 30 # Value in FPS
    shutter_speed: 200.0
    
  lidar:
    transform:
      location: { x: 0.0, y: 0.0, z: 2.4 }
      rotation: { pitch: 0.0, yaw: 0.0, roll: 0.0 }
    channels: 64
    range: 100
    points_per_second: 250000
    rotation_frequency: 20.0
    upper_fov: 10.0
    lower_fov: -30.0
    horizontal_fov: 360.0
    atmosphere_attenuation_rate: 0.004
    dropoff_general_rate: 0.45
    dropoff_intensity_limit: 0.8
    dropoff_zero_intensity: 0.4
    sensor_tick: 30 # Value in FPS
    noise_stddev: 0.0

traffic:
  number_of_vehicles: 50

display_manager:
  pygame_display: # It's better to match image_resize resolution
    display_width: 1280 
    display_height: 720
  grid_size: [1, 2]